### ISSUE TITLE
关于包名

### ISSUE THREAD

**Issue by WPNEAL** [vitoling/HiWeather#1]
请教大神:  
com.vito.work.hiweather.util.cnweather.APIURLEncoder.java 这个类的包名改了(weather改成了hiweather),但是代码中的package没有改,导致报错.(我看了下,同目录下的.kt也没有改,但是没有报错),而且同目录下的OfficialAPI.kt中调用了APIURLEncoder,没有import APIURLEncoder导致报错
初试kotlin,不知道是我哪里的配置问题吗???

**Comment by zhiyuan-l** [comment]
不是你配置的问题，是我之前改包名的时候没检查，现在已经改过来了，请拉取代码重试
